name: command_chain_timeline
description: A Flutter timeline for viewing exported command_chain log snapshots.
version: 0.2.0
repository: https://github.com/van4yta/command_chain_timeline

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  command_chain: ^0.2.0
  command_chain_logger: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
